# Builds js/service-areas.data.js — the localities of each bridal-prep service
# region — from the CBS locality list (data.gov.il, "רשימת ישובים").
#
#   curl -s "https://data.gov.il/api/3/action/datastore_search?resource_id=5c78e9fa-c2e2-4771-93ff-7f400a12f7ba&limit=2000" -o /tmp/loc.json
#   python3 -I scripts/build-service-areas.py /tmp/loc.json > js/service-areas.data.js
#
# Regions follow CBS sub-districts (נפה) and regional councils; the business
# rules (what counts as "בדרום", Herzliya in the Sharon too, ...) are below.
# Every other locality is kept, under `outside`, so the form recognizes it as
# a real place outside the service areas (e.g. Ashkelon) rather than a typo.

import json
import re
import sys

recs = json.load(open(sys.argv[1], encoding='utf-8'))['result']['records']


def clean(s):
    return re.sub(r'\s+', ' ', s or '').strip()


places = [(clean(r['שם_ישוב']), clean(r['שם_נפה']), clean(r['שם_מועצה'])) for r in recs]
places = [p for p in places if p[0]]

SUBDISTRICTS = {
    'sharon': {'השרון'},
    'hadera': {'חדרה'},
    'center': {'תל אביב', 'רמת גן', 'חולון', 'פתח תקווה'},
    'shfela': {'רחובות', 'רמלה'},
    'jerusalem': {'ירושלים'},
    'north': {'חיפה', 'עכו', 'עפולה', 'נצרת', 'כנרת', 'צפת', 'גולן'},
}
EXTRA = {
    # Filed under the Tel Aviv / Petah Tikva sub-districts, but "השרון" to everyone (and still in the center too).
    'sharon': {'הרצליה', 'רמת השרון', 'כפר סבא', 'רעננה', 'הוד השרון', 'כוכב יאיר-צור יגאל'},
    'south': {'אשדוד', 'קרית מלאכי'},        # the Ashdod area only; Ashkelon and further south are outside
}
COUNCILS = {'emek_hefer': {'עמק חפר'}, 'sharon': {'דרום השרון'}, 'south': {'באר טוביה'}}
ORDER = ['sharon', 'shfela', 'south', 'north', 'center', 'jerusalem', 'emek_hefer', 'hadera']

regions = {k: set() for k in ORDER}
for name, sub, council in places:
    for k in ORDER:
        if council in COUNCILS.get(k, ()) or name in EXTRA.get(k, ()):
            regions[k].add(name)
        elif sub in SUBDISTRICTS.get(k, ()) and not (k == 'sharon' and council == 'עמק חפר'):
            regions[k].add(name)

inside = set().union(*regions.values())
outside = sorted({p[0] for p in places} - inside)

out = ['// Generated by scripts/build-service-areas.py from the CBS locality list. Edit',
       '// the rules there and regenerate; a one-off fix by hand is fine too.',
       'export const REGION_PLACES = {']
for k in ORDER:
    out.append(f'  {k}: {json.dumps(sorted(regions[k]), ensure_ascii=False)},')
out.append('};')
out.append(f'export const OUTSIDE_PLACES = {json.dumps(outside, ensure_ascii=False)};')
print('\n'.join(out))
for k in ORDER:
    print(k, len(regions[k]), file=sys.stderr)
print('outside', len(outside), file=sys.stderr)
